// <auto-generated />
using System;
using DiaryPortfolio.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryPortfolio.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260925020028_add-column-IsHidden-Project")]
    partial class addcolumnIsHiddenProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.Attachment.ChatAttachmentFilesModel", b =>
                {
                    b.Property<Guid>("ChatAttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChatAttachmentId", "FileId");

                    b.HasIndex("FileId");

                    b.ToTable("ChatAttachmentFilesModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.Attachment.ChatAttachmentPhotoModel", b =>
                {
                    b.Property<Guid>("ChatAttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PhotoModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChatAttachmentId", "PhotoModelId");

                    b.HasIndex("PhotoModelId");

                    b.ToTable("ChatAttachmentPhotoModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.Attachment.ChatAttachmentVideoModel", b =>
                {
                    b.Property<Guid>("ChatAttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VideoModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChatAttachmentId", "VideoModelId");

                    b.HasIndex("VideoModelId");

                    b.ToTable("ChatAttachmentVideoModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.ChatAttachementModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId");

                    b.ToTable("ChatAttachements");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.ChatMessageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserModelId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.ConversationInfoModel", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConversationPhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConversationId");

                    b.HasIndex("ConversationPhotoId");

                    b.ToTable("ConversationInfo");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.ConversationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConversationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserModelId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.ConversationParticipantModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.HasIndex("UserModelId");

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.MessageReceiptModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId");

                    b.HasIndex("UserModelId");

                    b.ToTable("MessageReceipts");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.CityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.CollectionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ConditionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AvailableTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MediaId")
                        .IsUnique();

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.CustomUrlModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortfolioProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioProfileId");

                    b.ToTable("CustomUrls");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.DiaryProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DiaryProfile", (string)null);
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.EducationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Achievement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EducationFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortfolioProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EducationFileId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PortfolioProfileId");

                    b.HasIndex("SelectionId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ExperienceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortfolioProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PortfolioProfileId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.FileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SelectionId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.LocationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<Guid?>("PostalCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostalCodeId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.MediaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaStatusSelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaTypeSelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.HasIndex("MediaStatusSelectionId");

                    b.HasIndex("MediaTypeSelectionId");

                    b.HasIndex("SpaceId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.MediaPhotoModel", b =>
                {
                    b.Property<Guid>("MediaModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PhotoModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MediaModelId", "PhotoModelId");

                    b.HasIndex("PhotoModelId");

                    b.ToTable("MediaPhotoModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.MediaVideoModel", b =>
                {
                    b.Property<Guid>("MediaModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VideoModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MediaModelId", "VideoModelId");

                    b.HasIndex("VideoModelId");

                    b.ToTable("MediaVideoModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.PhotoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProfilePhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.HasIndex("ProfilePhotoId")
                        .IsUnique()
                        .HasFilter("[ProfilePhotoId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PortfolioProfile", (string)null);
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.PortfolioSectionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("H")
                        .HasColumnType("int");

                    b.Property<Guid>("PortfolioProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("W")
                        .HasColumnType("int");

                    b.Property<int?>("X")
                        .HasColumnType("int");

                    b.Property<int?>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioProfileId");

                    b.ToTable("PortfolioSections");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.PostalCodeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PostalCodes");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ProjectModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<Guid>("PortfolioProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioProfileId");

                    b.HasIndex("ProjectFileId");

                    b.HasIndex("ProjectTypeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ProjectPhotoModel", b =>
                {
                    b.Property<Guid>("ProjectModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PhotoModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectModelId", "PhotoModelId");

                    b.HasIndex("PhotoModelId");

                    b.ToTable("ProjectPhotoModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ProjectTypeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortfolioProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioProfileId");

                    b.ToTable("ProjectTypes");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ProjectVideoModel", b =>
                {
                    b.Property<Guid>("ProjectModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VideoModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectModelId", "VideoModelId");

                    b.HasIndex("VideoModelId");

                    b.ToTable("ProjectVideoModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ResumeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortfolioProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("PortfolioProfileId")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("Resume");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ResumeTemplateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResumeTemplate");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SelectionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Selection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Selections");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SkillModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortfolioProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioProfileId");

                    b.HasIndex("SelectionId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SpaceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiaryProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DiaryProfileId", "Title")
                        .IsUnique();

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.StateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.TypeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.VideoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.Attachment.ChatAttachmentFilesModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.Chat.ChatAttachementModel", "ChatAttachment")
                        .WithMany("FilesAttachment")
                        .HasForeignKey("ChatAttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.FileModel", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatAttachment");

                    b.Navigation("File");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.Attachment.ChatAttachmentPhotoModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.Chat.ChatAttachementModel", "ChatAttachment")
                        .WithMany("PhotosAttachment")
                        .HasForeignKey("ChatAttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.PhotoModel", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatAttachment");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.Attachment.ChatAttachmentVideoModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.Chat.ChatAttachementModel", "ChatAttachment")
                        .WithMany("VideosAttachment")
                        .HasForeignKey("ChatAttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.VideoModel", "Video")
                        .WithMany()
                        .HasForeignKey("VideoModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatAttachment");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.ChatAttachementModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.Chat.ChatMessageModel", "ChatMessage")
                        .WithMany()
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatMessage");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.ChatMessageModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.Chat.ConversationModel", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", "UserModel")
                        .WithMany()
                        .HasForeignKey("UserModelId");

                    b.Navigation("Conversation");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.ConversationInfoModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.Chat.ConversationModel", "Conversation")
                        .WithOne("ConversationInfo")
                        .HasForeignKey("DiaryPortfolio.Domain.Entities.Chat.ConversationInfoModel", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.PhotoModel", "ConversationPhoto")
                        .WithMany()
                        .HasForeignKey("ConversationPhotoId");

                    b.Navigation("Conversation");

                    b.Navigation("ConversationPhoto");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.ConversationModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", "UserModel")
                        .WithMany()
                        .HasForeignKey("UserModelId");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.ConversationParticipantModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.Chat.ConversationModel", "Conversation")
                        .WithOne("ConversationParticipant")
                        .HasForeignKey("DiaryPortfolio.Domain.Entities.Chat.ConversationParticipantModel", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", "UserModel")
                        .WithMany()
                        .HasForeignKey("UserModelId");

                    b.Navigation("Conversation");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.MessageReceiptModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.Chat.ChatMessageModel", "ChatMessage")
                        .WithMany()
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", "UserModel")
                        .WithMany()
                        .HasForeignKey("UserModelId");

                    b.Navigation("ChatMessage");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.CityModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.StateModel", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ConditionModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.MediaModel", "MediaModel")
                        .WithOne("ConditionModel")
                        .HasForeignKey("DiaryPortfolio.Domain.Entities.ConditionModel", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.CustomUrlModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", "PortfolioProfile")
                        .WithMany()
                        .HasForeignKey("PortfolioProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioProfile");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.DiaryProfileModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", "User")
                        .WithOne("DiaryProfile")
                        .HasForeignKey("DiaryPortfolio.Domain.Entities.DiaryProfileModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.EducationModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.FileModel", "EducationFile")
                        .WithMany()
                        .HasForeignKey("EducationFileId");

                    b.HasOne("DiaryPortfolio.Domain.Entities.LocationModel", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", "PortfolioProfile")
                        .WithMany()
                        .HasForeignKey("PortfolioProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.SelectionModel", "Selection")
                        .WithMany()
                        .HasForeignKey("SelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationFile");

                    b.Navigation("Location");

                    b.Navigation("PortfolioProfile");

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ExperienceModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.LocationModel", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", "PortfolioProfile")
                        .WithMany()
                        .HasForeignKey("PortfolioProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("PortfolioProfile");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.FileModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.SelectionModel", "Selection")
                        .WithMany()
                        .HasForeignKey("SelectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.LocationModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.PostalCodeModel", "PostalCode")
                        .WithMany("Locations")
                        .HasForeignKey("PostalCodeId");

                    b.Navigation("PostalCode");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.MediaModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.CollectionModel", "CollectionModel")
                        .WithMany("MediaModels")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiaryPortfolio.Domain.Entities.LocationModel", "LocationModel")
                        .WithOne()
                        .HasForeignKey("DiaryPortfolio.Domain.Entities.MediaModel", "LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiaryPortfolio.Domain.Entities.SelectionModel", "SelectionMediaStatusModel")
                        .WithMany()
                        .HasForeignKey("MediaStatusSelectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.SelectionModel", "SelectionMediaTypeModel")
                        .WithMany()
                        .HasForeignKey("MediaTypeSelectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.SpaceModel", "SpaceModel")
                        .WithMany("MediaModels")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionModel");

                    b.Navigation("LocationModel");

                    b.Navigation("SelectionMediaStatusModel");

                    b.Navigation("SelectionMediaTypeModel");

                    b.Navigation("SpaceModel");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.MediaPhotoModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.MediaModel", "Media")
                        .WithMany("MediaPhotos")
                        .HasForeignKey("MediaModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.PhotoModel", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.MediaVideoModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.MediaModel", "Media")
                        .WithMany("MediaVideos")
                        .HasForeignKey("MediaModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.VideoModel", "Video")
                        .WithMany()
                        .HasForeignKey("VideoModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.LocationModel", "Location")
                        .WithOne()
                        .HasForeignKey("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", "LocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DiaryPortfolio.Domain.Entities.PhotoModel", "ProfilePhoto")
                        .WithOne()
                        .HasForeignKey("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", "ProfilePhotoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", "User")
                        .WithOne("PortfolioProfile")
                        .HasForeignKey("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("ProfilePhoto");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.PortfolioSectionModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", "PortfolioProfile")
                        .WithMany("PortfolioSections")
                        .HasForeignKey("PortfolioProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioProfile");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.PostalCodeModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.CityModel", "City")
                        .WithMany("PostalCodes")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ProjectModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", "PortfolioProfile")
                        .WithMany()
                        .HasForeignKey("PortfolioProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.FileModel", "ProjectFile")
                        .WithMany()
                        .HasForeignKey("ProjectFileId");

                    b.HasOne("DiaryPortfolio.Domain.Entities.ProjectTypeModel", "ProjectType")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectTypeId");

                    b.Navigation("PortfolioProfile");

                    b.Navigation("ProjectFile");

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ProjectPhotoModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.PhotoModel", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.ProjectModel", "Project")
                        .WithMany("ProjectPhotos")
                        .HasForeignKey("ProjectModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ProjectTypeModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", "PortfolioProfile")
                        .WithMany()
                        .HasForeignKey("PortfolioProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioProfile");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ProjectVideoModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.ProjectModel", "Project")
                        .WithMany("ProjectVideos")
                        .HasForeignKey("ProjectModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.VideoModel", "Video")
                        .WithMany()
                        .HasForeignKey("VideoModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ResumeModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.FileModel", "ResumeFile")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", "PortfolioProfile")
                        .WithOne("Resume")
                        .HasForeignKey("DiaryPortfolio.Domain.Entities.ResumeModel", "PortfolioProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.ResumeTemplateModel", "ResumeTemplate")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PortfolioProfile");

                    b.Navigation("ResumeFile");

                    b.Navigation("ResumeTemplate");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SelectionModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.TypeModel", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SkillModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", "PortfolioProfile")
                        .WithMany()
                        .HasForeignKey("PortfolioProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.SelectionModel", "Selection")
                        .WithMany()
                        .HasForeignKey("SelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortfolioProfile");

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SpaceModel", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.DiaryProfileModel", "DiaryProfile")
                        .WithMany("SpaceModels")
                        .HasForeignKey("DiaryProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaryProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DiaryPortfolio.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.ChatAttachementModel", b =>
                {
                    b.Navigation("FilesAttachment");

                    b.Navigation("PhotosAttachment");

                    b.Navigation("VideosAttachment");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.Chat.ConversationModel", b =>
                {
                    b.Navigation("ConversationInfo");

                    b.Navigation("ConversationParticipant");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.CityModel", b =>
                {
                    b.Navigation("PostalCodes");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.CollectionModel", b =>
                {
                    b.Navigation("MediaModels");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.DiaryProfileModel", b =>
                {
                    b.Navigation("SpaceModels");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.MediaModel", b =>
                {
                    b.Navigation("ConditionModel");

                    b.Navigation("MediaPhotos");

                    b.Navigation("MediaVideos");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.PortfolioProfileModel", b =>
                {
                    b.Navigation("PortfolioSections");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.PostalCodeModel", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ProjectModel", b =>
                {
                    b.Navigation("ProjectPhotos");

                    b.Navigation("ProjectVideos");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.ProjectTypeModel", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.SpaceModel", b =>
                {
                    b.Navigation("MediaModels");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.StateModel", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("DiaryPortfolio.Domain.Entities.UserModel", b =>
                {
                    b.Navigation("DiaryProfile");

                    b.Navigation("PortfolioProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
